version: '2'
services:
  elastic:
    image: huanwei/elasticsearch:5.6.12
    container_name: elastic
    environment:
    - TZ='Asia/Shanghai'
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
    - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
    - 9200:9200
    - 9300:9300