spring:
  profiles:
    active: k8s
---
spring:
  profiles: development
  redis:
    host: 10.10.101.19
    port: 6379
  datasource:
    url: jdbc:mysql://10.10.101.19:3306/dev?useSSL=false
    username: root
    password: dbpass
    initialize: true
  zipkin:
    base-url: http://10.10.101.19:9411
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://10.10.101.19:8761/eureka/
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          semaphore:
            maxConcurrentRequests: 20
          thread:
            timeoutInMilliseconds: 600000
---
spring:
  profiles: docker
  redis:
    host: redis
    port: 6379
  datasource:
    url: jdbc:mysql://mysql:3306/dev?useSSL=false
    username: root
    password: dbpass
    initialize: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
---
spring:
  profiles: test
  redis:
    host: localhost
    port: 6379
  jpa:
    database: H2
  datasource:
    initialize: true
---
spring:
  profiles: k8s
  redis:
    host: ${REDIS_HOSTNAME:redis}
    port: ${REDIS_PORT:6379}
  datasource:
    url: jdbc:mysql://${MYSQL_HOSTNAME:mysql}:3306/dev?useSSL=false
    username: root
    password: dbpass
    initialize: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVICE_HOSTNAME:discovery-service}:8761/eureka/