server:
  port: 9411
  tomcat:
    uri-encoding: utf-8

spring:
  application:
    name: zipkin-server

zipkin:
  storage:
    type: elasticsearch
    elasticsearch:
      hosts: http://10.10.101.19:9200
      cluster: docker-cluster
      index: zipkin
      index-shards: 1
      index-replicas: 1
  collector:
    kafka:
      bootstrap-servers: 10.10.101.19:9092
      zookeeper: 10.10.101.19:2181
      topic: zipkin

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  metrics:
    web:
      server:
        auto-time-requests: false