spring:
  profiles:
    active: development
---
spring:
  profiles: development
  application:
    name: online-store-web
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
zuul:
  host:
    connect-timeout-millis: 60000
  ignored-services: '*'
  routes:
    edge-service:
      path: /api/**
      url: http://10.10.101.20:9999
    auth-service:
      path: /user/**
      url: http://10.10.101.20:8181/uaa/user
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 12000
security:
  enable-csrf: false
  oauth2:
    resource:
      userInfoUri: http://10.10.101.20:8181/uaa/user
    client:
      accessTokenUri: http://10.10.101.20:8181/uaa/oauth/token
      userAuthorizationUri: http://10.10.101.20:8181/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
  ignored: /assets/**
eureka:
  instance:
    non-secure-port: 8787
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://10.10.101.19:8761/eureka/
---
spring:
  profiles: docker
  application:
    name: online-store-web
zuul:
  ignored-services: '*'
  routes:
    edge-service:
      path: /api/**
      url: http://${DOCKER_IP:192.168.99.100}:9999
    auth-service:
      path: /user/**
      url: http://${DOCKER_IP:192.168.99.100}:8181/uaa/user
security:
  enable-csrf: false
  oauth2:
    resource:
      userInfoUri: http://${DOCKER_IP:192.168.99.100}:8181/uaa/user
    client:
      accessTokenUri: http://${DOCKER_IP:192.168.99.100}:8181/uaa/oauth/token
      userAuthorizationUri: http://${DOCKER_IP:192.168.99.100}:8181/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
eureka:
  instance:
    non-secure-port: 8787
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/