server:
  port: 20000
eureka:
  client:
    service-url:
      defaultZone: http://10.10.101.19:8761/eureka
spring:
  application:
    name: Turbine
turbine:
  aggregator:
    clusterConfig: default # 监听的集群(cluster)
  clusterNameExpression: new String("default") # 集群表达式
  # 监听的服务id
  #  app-config: ONLINE-STORE-WEB, USER-SERVICE, INVENTORY-SERVICE

#  对于turbine.clusterNameExpression，
#  若值为new String(“default”)，则会监听所有的服务，并turbine.aggregator.clusterConfig的值应为default。
#  若值为metadata[‘cluster’]，则被监听的服务应该配置eureka.instance.metadata-map.cluster=xxx，clusterConfig需要配置xxx，
#  若有多个集群，则clusterConfig=xxx, xxx，且流访问地址http://{host}:{port}/turbine.stream应当附带参数cluster=xxx监听单独的集群，不再支持不带参数的访问方式。（host为Turbine所在主机，port为Turbine所在端口）