spring.profiles.active: development
---
spring:
  profiles: development
  data:
    mongodb:
      host: 10.10.101.19
      port: 27017
  jackson:
    date-format: "YYYY-MM-dd"
    serialization:
      write_dates_as_timestamps: true
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    sender:
      type: kafka
    kafka:
      topic: zipkin
  kafka:
    bootstrap-servers: 10.10.101.19:9092
security:
  oauth2:
    resource:
      userInfoUri: http://192.168.99.100:8181/uaa/user
    client:
      client-id: acme
  ignored: /api/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://10.10.101.19:8761/eureka/
---
spring:
  profiles: docker
  data:
    mongodb:
      host: 10.10.101.19
      port: 27017
  mvc:
    date-format: "YYYY-MM-dd"
  jackson:
    date-format: "YYYY-MM-dd"
    serialization:
      write_dates_as_timestamps: true
security:
  oauth2:
    resource:
      userInfoUri: http://${DOCKER_IP:192.168.99.100}:8181/uaa/user
    client:
      client-id: acme
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/